swagger: "2.0"
info:
  title: data types for NSSO employer identifiers
  version: v1beta
paths: {}
definitions:
  NssoNumber:
    description: Identifier issued by NSSO (RSZ/NSSO) for an employer
    type: string
    pattern: '\d{9}'
    # consists of 7 digits plus 2 check digits
    # TODO: is this also used for RSZPPO numbers? in current services, it seems to be. Does it need an additional field (RSZPPO yes/no) to be unique across RSZ+RSZ-PPO
  NssoNumberIncludingProvisional:
    description: Identifier issued by NSSO for an employer, including both definitive and provisional identifiers
    type: string
    pattern: '5?\d{9}'
    # definitive identifiers have length 9, provisional ones length 10 and start with 5
    