swagger: "2.0"
info:
  title: data types for NSSO employer identifiers
  version: v1beta
paths: {}
definitions:
  EmployerId:
    description: Identifier issued by NSSO (RSZ/NSSO) for an employer
    type: string
    pattern: [0,5]{0-1}\d{9} #TODO: verify. String with leading zeros or integer type? If integer, can pattern be applied?