swagger: "2.0"
info:
  title: data types for NSSO employer identifiers
  version: v1beta
paths: {}
definitions:
  EmployerId:
    description: Definitive or provisional NSSO number, assigned to each registered employer or local or provincial administration.
    type: string
    pattern: '^5?\d{9}$' #TODO: verify pattern. String with mandatory, optional or no leading zeros or integer type? If integer, no pattern can be applied.