swagger: "2.0"
info:
  title: data types related to time
  version: v1beta
paths: {}
definitions:
  Year:
    description: A year in the Gregorian Calendar
    type: string
    pattern: '^[0-9]{4}$'
    example: '2020'
