swagger: "2.0"
info:
  title: data types related to organizations
  version: v1beta
paths: {}
definitions:
  CbeNumber:
    description: Identifier issued by CBE, either identifying a site (establishment unit) or enterprise
    type: string
    pattern: '[0-8]\d{9}'
    #TODO: descriptions to synchronize with vocabularies
  EnterpriseNumber:
    description: Enterprise number issued by CBE for registered organizations/entities
    type: string
    pattern: '[0|1]\d{9}'
  EstablishmentUnitNumber:
    description: Number issued by CBE identifying an establishment/site of an organization 
    type: string
    pattern: '[2-8]\d{9}'
#TODO: add nsso registration number => input from NSSO/Smals.