# Maven continuous integration build of the guide
name: maven-ci-build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Adopt OpenJDK 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '11'
    - name: Build with Maven
      run: mvn -B site